### ISSUE TITLE
mock request/response mismatch

### ISSUE THREAD

**Issue by DerManoMann** [pact-foundation/pact-php#34]
I am currently testing some edge cases in our app and came across an issue where the Path predicate can't match request and response...

The original project name in the test is ````'i(nde?x3'```` which arguably is not great. Nevertheless, it should work IMO.

````
RuntimeException: No mock responses for were found for this request: 
A DELETE request with URL: http://localhost
	has path: /v0.1/projects/i%28nde%3Fx3
	has port: 
	has query: 
	has headers: 
		Content-Type with value application/json
````

The string gets urlencode()'ed before use, so the question mark does actually work as part of the path.

I debugged the path predicate and after normalizeRequest() et al the path looks like this: ````'i(nde%3Fx3'````. 

Is this the expected behaviour?

**Comment by mattermack** [comment]
Wow, that's a use case for you.  I also agree that it _should_ work.   I know that we actually parse out the ? to set the query variable but I'd have to look at it in detail.  

Is this on the Provider side or the Consumer side?

We ported the Consumer side to the Ruby backend.  Try this branch if it is on the Consumer side: https://github.com/pact-foundation/pact-php/tree/migrate-to-ruby-backend

Otherwise, I'll be traveling this week and can look at it next week.   If you run into an issue, I can probably look at a pull request too!

**Comment by DerManoMann** [comment]
This is on the consumer side using guzzle as http client, so those request/response instances comde from there.

In real life the url does work, encoding and all...

Not sure I have time ATM to try the new backend, but I'll try to find some.

**Comment by cfmack** [comment]
I'll see if I can replicate your issue this week, perhaps on a plane this
week.

**Comment by DerManoMann** [comment]
Sounds good. It's not too important for me ATM, however it seems strange as encoding/decoding should result in the same path...

Did a quick ````git checkout -b origin/migrate-to-ruby-backend```` in my vendor folder and ran the test again - same result. Was that all you were asking or is there anything else I need to do?

I should perhaps add that I do not really use the local mock server at all. I use the guzzle mock history middleware (http://docs.guzzlephp.org/en/stable/testing.html#history-middleware) to capture request/response pairs from my tests and then stuff them into a mock service. (as per issue #28)

**Comment by mattermack** [comment]
With the move to Pact PHP 3 and the Ruby backend, we can revisit this later if we need to.
