### ISSUE TITLE
Proposal to add features to work with provider state

### ISSUE THREAD

**Issue by arkonchik** [pact-foundation/pact-php#77]
I can try to do pull request with feature to work with provider state like the gherkin language work's
(http://behat.org/en/latest/user_guide/gherkin.html).
The main idea to map some state context to literal string state from consumer expectation. 

The code that load provider state may be similar to
```
$stateMatcher = new StateMatcher()
$stateMatcher->addStateContext(new StateContext());
$this->stateMatcher->load('User with id 223 and default data');


   /**
    * Load method signature
     * @param string $providerState
     * @param string $stateDelimiter
     */
    public function load(string $providerState, $stateDelimiter = 'And')
    {


class StateContext implements StateContextInterface
{
    /**
     * @Given(name="/User with id (\d+)/")
     */
    public function methodThatLoadStateForUser(int $id)
    {
    }

    /**
     * @Given(name="/Another step/")
     */
    public function methodWithAnotherState()
    {

    }
}
```
And this mechanism can be compatible with pact v3 specification too after some refinement.

Syntax of methods that load state can be one of this:
```
/**
     * @Given(name="/Another step/", consumer={"MyConsumer", "AnotherConsumer"})
     */
    public function methodWithAnotherState()
    {

    }
```

or

```
   /**
     * @Given /Another step/
     */
    public function methodWithAnotherState()
    {

    }
```
Is this good idea?

**Comment by arkonchik** [comment]
The idea is not clear? :)

**Comment by cfmack** [comment]
I can check in about a week

**Comment by mattermack** [comment]
Reading your description, I think this would be a good approach to handling state.  That way we can map this idea back to the setProviderState description.   Moving from Php Pact 2.0 to Php Pact 3.x, we now make web calls to the Ruby backend (I am sure you realize this at this point).   In that move, I think Php lost a little bit of control over states.   Anything that can help clarify this would be a good thing.

**Comment by YOU54F** [comment]
Thanks and sorry for the delay, going to close this ticket off due to age.

If this feature is still of interest to anyone, I would suggest to,

Please try out state handlers which support both multiple provider states and parameterisation from Pact-Specification V3+ available in pact-php alpha v10+

https://github.com/pact-foundation/pact-php/blob/master/docs/consumer.md#build-the-interaction
https://github.com/pact-foundation/pact-php/blob/master/docs/provider.md#create-unit-test

If anyone still feels this proposal would be useful, feel free to comment back and we can re-open.

As a side note, we are leveraging cucumber in the [pact-compatability-suite](https://github.com/pact-foundation/pact-compatibility-suite) now as part of pact-php ([code](https://github.com/pact-foundation/pact-php/tree/master/compatibility-suite)) which may be worth a look at
